using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.7.1926.0")]
[assembly: AssemblyProductAttribute("Sxta1516")]
[assembly: AssemblyTitleAttribute("A Dynamic Compiler for Sxta.Rti1516")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2006-07, Agustin Santos Mendez")]
[assembly: AssemblyCompanyAttribute("Sxta")]
[assembly: AssemblyTrademarkAttribute("")]

