using System;
using System.Collections.Generic;
using System.Text;

namespace Sxta.Rti1516.Management
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;
    //using Sxta.Rti1516.Interactions;

    ///<summary>
    ///State of the federate. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Management Object Model </author>
    [HLAEnumeratedData(Name = "HLAfederateState",
                    Representation = "HLAinteger32BE",
                    Semantics = "State of the federate.")]
    public enum HLAfederateState
    {
        ActiveFederate = 1,
        FederateSaveInProgress = 3,
        FederateRestoreInProgress = 5
    }


    ///<summary>
    ///State of time advancement. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Management Object Model </author>
    [HLAEnumeratedData(Name = "HLAtimeState",
                    Representation = "HLAinteger32BE",
                    Semantics = "State of time advancement.")]
    public enum HLAtimeState
    {
        TimeGranted = 0,
        TimeAdvancing = 1
    }

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Management Object Model </author>
    public interface IHLAfederate : IHLAmanager
    {
        ///<summary>Gets/Sets the value of the HLAfederateHandle attribute.</summary>
        HLAfederateHandle HLAfederateHandle
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAfederateType attribute.</summary>
        String HLAfederateType
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAfederateHost attribute.</summary>
        String HLAfederateHost
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLARTIversion attribute.</summary>
        String HLARTIversion
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAFDDID attribute.</summary>
        String HLAFDDID
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAtimeConstrained attribute.</summary>
        bool HLAtimeConstrained
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAtimeRegulating attribute.</summary>
        bool HLAtimeRegulating
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAasynchronousDelivery attribute.</summary>
        bool HLAasynchronousDelivery
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAfederateState attribute.</summary>
        HLAfederateState HLAfederateState
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAtimeManagerState attribute.</summary>
        HLAtimeState HLAtimeManagerState
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAlogicalTime attribute.</summary>
        ILogicalTime HLAlogicalTime
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAlookahead attribute.</summary>
        ILogicalTimeInterval HLAlookahead
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAGALT attribute.</summary>
        ILogicalTime HLAGALT
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLALITS attribute.</summary>
        ILogicalTime HLALITS
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAROlength attribute.</summary>
        int HLAROlength
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLATSOlength attribute.</summary>
        int HLATSOlength
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAreflectionsReceived attribute.</summary>
        int HLAreflectionsReceived
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAupdatesSent attribute.</summary>
        int HLAupdatesSent
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAinteractionsReceived attribute.</summary>
        int HLAinteractionsReceived
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAinteractionsSent attribute.</summary>
        int HLAinteractionsSent
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectsInstancesThatCanBeDeleted attribute.</summary>
        int HLAobjectsInstancesThatCanBeDeleted
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesUpdated attribute.</summary>
        int HLAobjectInstancesUpdated
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesReflected attribute.</summary>
        int HLAobjectInstancesReflected
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesDeleted attribute.</summary>
        int HLAobjectInstancesDeleted
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesRemoved attribute.</summary>
        int HLAobjectInstancesRemoved
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesRegistered attribute.</summary>
        int HLAobjectInstancesRegistered
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAobjectInstancesDiscovered attribute.</summary>
        int HLAobjectInstancesDiscovered
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAtimeGrantedTime attribute.</summary>
        int HLAtimeGrantedTime
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAtimeAdvancingTime attribute.</summary>
        int HLAtimeAdvancingTime
        {
            get;
            set;
        }
    }
}
