namespace Sxta.Rti1516.BoidSample
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;
    using Sxta.Rti1516.Serializers.XrtiEncoding;
    using Sxta.Rti1516.BoostrapProtocol;
    using Sxta.Rti1516.Interactions;
    using Sxta.Rti1516.XrtiHandles;

    ///<summary>
    ///Autogenerated interaction and serializer registration Helper. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Hello World Object Model </author>
    [HLAinteractionHelperAttribute(Name = "BoidObjectModelInteractionHelper",
                                   FomName = "Boids Object Model",
                                   Semantics = "A Listener Manager and serializer manager")]
    public class BoidObjectModelInteractionHelper
    {
        InteractionManager manager;

        /// <summary>Constructor.</summary>
        /// <param name="interactionManager"> the run-time interaction manager</param>
        public BoidObjectModelInteractionHelper(InteractionManager interactionManager)
        {
            Type objType;
            manager = interactionManager;
            XrtiSerializerManager serializerMngr = manager.SerializerManager;
            long handle;
            ObjectClassDescriptor ocd;


            ocd = manager.DescriptorManager.GetObjectClassDescriptor("Boid");
            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("Color").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new BoidPropertyColorXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("Position").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new BoidPropertyPositionXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("Velocity").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new BoidPropertyVelocityXrtiSerializer(serializerMngr));

        }

        /// <summary>Notifies the listener of a received interaction.</summary>
        /// <param name="msg"> the message of the received interaction</param>
        public void ReceiveInteraction(BaseInteractionMessage msg)
        {
            try
            {
                /*
                if (msg is CommunicationMessage)
                {
                    foreach (IInteractionListener il in manager.InteractionListeners)
                    {
                        if (il is IHelloWorldObjectModelInteractionListener)
                            (il as IHelloWorldObjectModelInteractionListener).OnReceiveCommunication(msg as CommunicationMessage);
                        else
                            il.ReceiveInteraction(msg);
                    }
                }
                else
                */
                foreach (IInteractionListener il in manager.InteractionListeners)
                {
                    il.ReceiveInteraction(msg);
                }
            }
            catch (System.IO.IOException ioe)
            {
                throw new FederateInternalError(ioe.ToString());
            }

        }
    }
}
