namespace Sxta.Rti1516.Reflection
{
    using System;

    using Hla.Rti1516;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Reflection Object Model </author>
    public interface IHLAattribute : IHLAreflection
    {

        ///<summary>Gets/Sets the value of the dataType attribute.</summary>
        String DataType
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the dataTypeNotes attribute.</summary>
        String DataTypeNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the updateType attribute.</summary>
        HLAupdateType UpdateType
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the updateTypeNotes attribute.</summary>
        String UpdateTypeNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the updateCondition attribute.</summary>
        String UpdateCondition
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the updateConditionNotes attribute.</summary>
        String UpdateConditionNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the ownership attribute.</summary>
        HLAownershipType Ownership
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the ownershipNotes attribute.</summary>
        String OwnershipNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the sharing attribute.</summary>
        HLAsharingType Sharing
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the sharingNotes attribute.</summary>
        String SharingNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the dimensions attribute.</summary>
        String Dimensions
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the dimensionsNotes attribute.</summary>
        String DimensionsNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the transportation attribute.</summary>
        String Transportation
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the transportationNotes attribute.</summary>
        String TransportationNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the order attribute.</summary>
        HLAorderType Order
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the orderNotes attribute.</summary>
        String OrderNotes
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the semantics attribute.</summary>
        String Semantics
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the semanticsNotes attribute.</summary>
        String SemanticsNotes
        {
            get;
            set;
        }
    }
}
