namespace Sxta.Rti1516.Reflection
{
    using System;

    using Hla.Rti1516;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Reflection Object Model </author>
    public interface IHLAobjectRoot
    {
    }
}
