namespace Sxta.Rti1516.Reflection
{
    using System;

    using Hla.Rti1516;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Reflection Object Model </author>
    public interface IHLAreflection : IHLAobjectRoot
    {

        ///<summary>Gets/Sets the value of the reflectionName attribute.</summary>
        String Name
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the reflectionNameNotes attribute.</summary>
        String NameNotes
        {
            get;
            set;
        }
    }
}
