namespace Sxta.Rti1516.Proxies
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Meta-Federation Object Model </author>
    public interface IHLAobjectRoot
    {
    }
}
