namespace Sxta.Rti1516.Proxies
{

    using Hla.Rti1516;
    using System;

    ///<summary>
    ///Autogenerated object instance listener interface. 
    ///</summary>
    /// <author> Sxta.Rti1516.Compiler.ProxyCompiler</author>
    public interface IHLAinteractionClassListener
    {

        /// <summary>Notifies the listener that the parents attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void ParentsUpdated(IHLAinteractionClass source,
                                   String oldValue,
                                   String newValue,
                                   byte[] userSuppliedTag,
                                   OrderType sentOrdering,
                                   TransportationType theTransport);

        /// <summary>Notifies the listener that the sharing attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void SharingUpdated(IHLAinteractionClass source,
                                  Sxta.Rti1516.Reflection.HLAsharingType oldValue,
                                   Sxta.Rti1516.Reflection.HLAsharingType newValue,
                                   byte[] userSuppliedTag,
                                   OrderType sentOrdering,
                                   TransportationType theTransport);

        /// <summary>Notifies the listener that the dimensions attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void DimensionsUpdated(IHLAinteractionClass source,
                                      String oldValue,
                                      String newValue,
                                      byte[] userSuppliedTag,
                                      OrderType sentOrdering,
                                      TransportationType theTransport);

        /// <summary>Notifies the listener that the transportation attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void TransportationUpdated(IHLAinteractionClass source,
                                          String oldValue,
                                          String newValue,
                                          byte[] userSuppliedTag,
                                          OrderType sentOrdering,
                                          TransportationType theTransport);

        /// <summary>Notifies the listener that the order attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void OrderUpdated(IHLAinteractionClass source,
                                Sxta.Rti1516.Reflection.HLAorderType oldValue,
                                 Sxta.Rti1516.Reflection.HLAorderType newValue,
                                 byte[] userSuppliedTag,
                                 OrderType sentOrdering,
                                 TransportationType theTransport);

        /// <summary>Notifies the listener that the parameters attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void ParametersUpdated(IHLAinteractionClass source,
                                      long[] oldValue,
                                      long[] newValue,
                                      byte[] userSuppliedTag,
                                      OrderType sentOrdering,
                                      TransportationType theTransport);

        /// <summary>Notifies the listener that the semantics attribute has been updated.</summary>
        ///
        /// <param name="source"> the source of the notification</param>
        /// <param name="oldValue"> the old value of the attribute</param>
        /// <param name="newValue"> the new value of the attribute</param>
        /// <param name="userSuppliedTag"> the user-supplied tag associated with the update</param>
        /// <param name="sentOrdering"> the type of ordering with which the update was sent</param>
        /// <param name="theTransport"> the type of transport associated with the update</param>
        void SemanticsUpdated(IHLAinteractionClass source,
                                     String oldValue,
                                     String newValue,
                                     byte[] userSuppliedTag,
                                     OrderType sentOrdering,
                                     TransportationType theTransport);
    }
}
