namespace Sxta.Rti1516.Management
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;
    using Sxta.Rti1516.Interactions;
    using Sxta.Rti1516.Base; //TODO

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Management Object Model </author>
    public interface IHLAfederation : IHLAmanager
    {

        ///<summary>Gets/Sets the value of the HLAfederationName attribute.</summary>
        String HLAfederationName
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAfederatesinFederation attribute.</summary>
        HLAhandleList HLAfederatesinFederation
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLARTIversion attribute.</summary>
        String HLARTIversion
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAFDDID attribute.</summary>
        String HLAFDDID
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAlastSaveName attribute.</summary>
        String HLAlastSaveName
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAlastSaveTime attribute.</summary>
        ILogicalTime HLAlastSaveTime
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAnextSaveName attribute.</summary>
        String HLAnextSaveName
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAnextSaveTime attribute.</summary>
        ILogicalTime HLAnextSaveTime
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAautoProvide attribute.</summary>
        HLAswitch HLAautoProvide
        {
            get;
            set;
        }

        ///<summary>Gets/Sets the value of the HLAconveyRegionDesignatorSets attribute.</summary>
        HLAswitch HLAconveyRegionDesignatorSets
        {
            get;
            set;
        }
    }
}
