namespace Sxta.Rti1516.MetaFederation
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Meta-Federation Object Model </author>
    public interface IHLAfederationExecution : IHLAmetaFederation
    {

        ///<summary>Gets/Sets the value of the federationName attribute.</summary>
        String FederationName
        {
            get;
            set;
        }
    }
}
