namespace Sxta.Rti1516.Management
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;

    ///<summary>
    ///Autogenerated object instance interface. 
    ///</summary>
    /// <author> Sxta1516.DynamicCompiler.DynamicCompiler from Management Object Model </author>
    public interface IHLAmanager : IHLAobjectRoot
    {
    }
}
