namespace Sxta.Rti1516.Management
{
    using System;

    using Hla.Rti1516;
    using Sxta.Rti1516.Reflection;
    using Sxta.Rti1516.Serializers.XrtiEncoding;
    using Sxta.Rti1516.BoostrapProtocol;
    using Sxta.Rti1516.Interactions;
    using Sxta.Rti1516.XrtiHandles;

    ///<summary>
    ///Autogenerated interaction and serializer registration Helper. 
    ///</summary>
    /// <author> ANGEL </author>
    [HLAinteractionHelperAttribute(Name = "SxtaObjectModelInteractionHelper",
                                   FomName = "Sxta Object Model",
                                   Semantics = "A Listener Manager and serializer manager")]
    public class SxtaObjectModelInteractionHelper
    {
        InteractionManager manager;

        /// <summary>Constructor.</summary>
        /// <param name="interactionManager"> the run-time interaction manager</param>
        public SxtaObjectModelInteractionHelper(InteractionManager interactionManager)
        {
            Type objType;
            manager = interactionManager;
            XrtiSerializerManager serializerMngr = manager.SerializerManager;
            long handle;
            ObjectClassDescriptor ocd;

            ocd = manager.DescriptorManager.GetObjectClassDescriptor("Sxtafederate");

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAisJoined").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAisJoinedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAfederateHandle").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAfederateHandleXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAfederateType").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAfederateTypeXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAfederateHost").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAfederateHostXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAtimeRegulating").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAtimeRegulatingXrtiSerializer(serializerMngr));

            /*
            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLARTIversion").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLARTIversionXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAFDDID").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAFDDIDXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAtimeConstrained").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAtimeConstrainedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAasynchronousDelivery").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAasynchronousDeliveryXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAfederateState").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAfederateStateXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAtimeManagerState").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAtimeManagerStateXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAlogicalTime").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAlogicalTimeXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAlookahead").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAlookaheadXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAGALT").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAGALTXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLALITS").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLALITSXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAROlength").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAROlengthXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLATSOlength").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLATSOlengthXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAreflectionsReceived").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAreflectionsReceivedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAupdatesSent").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAupdatesSentXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAinteractionsReceived").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAinteractionsReceivedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAinteractionsSent").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAinteractionsSentXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectsInstancesThatCanBeDeleted").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectsInstancesThatCanBeDeletedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesUpdated").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesUpdatedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesReflected").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesReflectedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesDeleted").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesDeletedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesRemoved").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesRemovedXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesRegistered").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesRegisteredXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAobjectInstancesDiscovered").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAobjectInstancesDiscoveredXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAtimeGrantedTime").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAtimeGrantedTimeXrtiSerializer(serializerMngr));

            handle = ((XRTIAttributeHandle)ocd.GetAttributeDescriptor("HLAtimeAdvancingTime").Handle).Identifier;
            serializerMngr.RegisterSerializer(null, handle, new HLAfederatePropertyHLAtimeAdvancingTimeXrtiSerializer(serializerMngr));
            */
        }

        /// <summary>Notifies the listener of a received interaction.</summary>
        /// <param name="msg"> the message of the received interaction</param>
        public void ReceiveInteraction(BaseInteractionMessage msg)
        {
            try
            {
                foreach (IInteractionListener il in manager.InteractionListeners)
                {
                    il.ReceiveInteraction(msg);
                }
            }
            catch (System.IO.IOException ioe)
            {
                throw new FederateInternalError(ioe.ToString());
            }

        }
    }
}
